const ARABIC_REGIONS: string[] = [
  "saudi arabia",
  "السعودية",
  "السعودية العربية",
  "united arab emirates",
  "uae",
  "الإمارات",
  "الإمارات العربية المتحدة",
  "kuwait",
  "الكويت",
  "qatar",
  "قطر",
  "bahrain",
  "البحرين",
  "oman",
  "عُمان",
  "عمان",
  "jordan",
  "الأردن",
  "lebanon",
  "لبنان",
  "syria",
  "سوريا",
  "الجمهورية العربية السورية",
  "iraq",
  "العراق",
  "yemen",
  "اليمن",
  "palestine",
  "فلسطين",
  "egypt",
  "مصر",
  "sudan",
  "السودان",
  "libya",
  "ليبيا",
  "tunisia",
  "تونس",
  "algeria",
  "الجزائر",
  "morocco",
  "المغرب",
  "mauritania",
  "موريتانيا",
  "somalia",
  "الصومال",
  "djibouti",
  "جيبوتي",
  "comoros",
  "جزر القمر",
  "riyadh",
  "الرياض",
  "jeddah",
  "جدة",
  "dubai",
  "دبي",
  "abu dhabi",
  "أبوظبي",
  "doha",
  "الدوحة",
  "manama",
  "المنامة",
  "muscat",
  "مسقط",
  "amman",
  "عمان",
  "beirut",
  "بيروت",
  "damascus",
  "دمشق",
  "baghdad",
  "بغداد",
  "sanaa",
  "صنعاء",
  "gaza",
  "غزة",
  "cairo",
  "القاهرة",
  "khartoum",
  "الخرطوم",
  "tripoli",
  "طرابلس",
  "tunis",
  "تونس العاصمة",
  "algiers",
  "الجزائر العاصمة",
  "rabat",
  "الرباط",
  "nouakchott",
  "نواكشوط",
  "mogadishu",
  "مقديشو",
];

export function suggestLanguageFromLocation(location?: string): "ar-first" | "en-first" {
  if (!location || location.trim() === "") return "en-first";
  const lower = location.toLowerCase();
  for (const region of ARABIC_REGIONS) {
    if (lower.includes(region.toLowerCase())) return "ar-first";
  }
  return "en-first";
}